steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'europe-docker.pkg.dev/squad-a1/reskilling-hackathon-backend/demo-api:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-docker.pkg.dev/squad-a1/reskilling-hackathon-backend/demo-api:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args: [
      'run', 
      'deploy', 
      'backend', 
      '--image', 
      'europe-docker.pkg.dev/squad-a1/reskilling-hackathon-backend/demo-api:$SHORT_SHA',
      '--region', 
      'europe-southwest1', 
      '--service-account', 
      'hackaton-sa@squad-a1.iam.gserviceaccount.com',
      '--port',
      '8080',
      '--set-secrets',
      'SPRING_DATASOURCE_USERNAME=SPRING_DATASOURCE_USERNAME:latest,SPRING_DATASOURCE_PASSWORD=SPRING_DATASOURCE_PASSWORD:latest'


    ]

options:
  logging: CLOUD_LOGGING_ONLY






 
